-- Exercise demonstration media + form cues, shown when a user taps an
-- exercise on the Progressie tab (and the Schema tab's day detail). Global
-- reference content, not user data: one row per exercise name from the
-- generator's catalog (packages/program-generator/src/exercises.ts),
-- imported once here rather than fetched live from a third party on every
-- page view.
--
-- Source: free-exercise-db (https://github.com/yuhonas/free-exercise-db),
-- Unlicense (public domain) — no attribution legally required, but the
-- source is recorded per-row anyway for traceability. Chosen over the
-- alternatives researched (ExerciseDB API: AGPL-3.0 + paid tiers + no
-- bundleable media, hotlinked from their CDN; hasaneyldrm/exercises-dataset:
-- MIT for the dataset structure but the media itself is © Gym visual,
-- "redistributed with permission" and NOT freely redistributable — too much
-- licensing risk for media we'd be re-serving) — free-exercise-db is public
-- domain top to bottom, self-hostable (bundled JPGs in the repo, currently
-- referenced via their raw.githubusercontent.com URLs), has both media and
-- textual instructions in one dataset, and needs no API key.
--
-- Matching was done by hand against our own ~70-exercise catalog (not a
-- generic fuzzy-match at runtime): only exact movement+equipment matches
-- were used, so roughly a third of our catalog (mostly Dutch-only variants
-- like "Calf Raise op trede", or exercises this particular dataset simply
-- doesn't have, e.g. plain "Push-up"/"Pull-up") intentionally has no row
-- here — those fall back to the app's plain "not available yet" state
-- instead of showing a mismatched exercise. The "Let op" tips are original
-- Dutch text written for this app (informed by standard lifting-technique
-- knowledge and cross-checked against this dataset's own step-by-step
-- instructions), not a translation of the source's English text.

create table exercise_media (
  id uuid primary key default gen_random_uuid(),
  exercise_name text not null unique,
  media_urls text[] not null,
  tips text[] not null,
  source_name text not null,
  source_url text not null,
  source_license text not null,
  created_at timestamptz not null default now()
);

alter table exercise_media enable row level security;

-- Read-only shared reference content — every authenticated user sees the same
-- rows. No insert/update/delete policy: this table is only ever written by
-- migrations (re-importing is a deliberate, occasional maintenance action,
-- not something the app does at runtime).
create policy "Authenticated users read exercise media" on exercise_media
  for select to authenticated using (true);

insert into exercise_media (exercise_name, media_urls, tips, source_name, source_url, source_license) values
  ('Barbell Squat', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/1.jpg'], array['Houd je borst omhoog en je rug recht — laat de romp niet naar voren klappen.', 'Zak tot je heupen net onder kniehoogte komen; dieper mag als je mobiliteit dat toelaat.', 'Duw door je hielen omhoog, niet door je tenen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Goblet Squat', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/1.jpg'], array['Houd de dumbbell dicht tegen je borst, beide handen onder de kop.', 'Ellebogen wijzen naar binnen, tussen je knieën door bij het diepste punt.', 'Het gewicht voorop dwingt je vanzelf tot een rechte romp — laat dat zijn werk doen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Bodyweight Squat', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Squat/1.jpg'], array['Voeten schouderbreedte uit elkaar, tenen licht naar buiten.', 'Knieën volgen de richting van je tenen — laat ze niet naar binnen zakken.', 'Kom omhoog door je hielen actief in de vloer te drukken.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Leg Press', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/1.jpg'], array['Zet je voeten schouderbreedte op de plaat, niet te hoog en niet te laag.', 'Laat je onderrug niet van de rugleuning loskomen bij het diepste punt.', 'Blokkeer je knieën nooit volledig bovenaan — houd een lichte buiging.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Lunge', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/1.jpg'], array['Stap ver genoeg naar voren zodat je voorste knie niet voorbij je tenen komt.', 'Laat je achterste knie bijna de grond raken, gecontroleerd.', 'Houd je romp rechtop — leun niet naar voren.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Barbell Deadlift', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/1.jpg'], array['Houd de stang dicht tegen je schenen en dijen tijdens de hele beweging.', 'Span je rug voordat je optrekt — een bolle rug is de meest voorkomende fout.', 'Kom omhoog door je heupen naar voren te duwen, niet door alleen je rug te strekken.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Single-Leg Glute Bridge', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Glute_Bridge/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Glute_Bridge/1.jpg'], array['Duw door je hiel van het steunende been, niet door je tenen.', 'Houd je heupen recht — laat de niet-steunende kant niet zakken.', 'Knijp bovenin je bilspier bewust samen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Barbell Romanian Deadlift', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/1.jpg'], array['Buig vanuit je heupen, niet vanuit je onderrug — knieën blijven licht gebogen.', 'Houd de stang zo dicht mogelijk langs je benen.', 'Ga zo diep als je hamstrings toelaten zonder je rug te bollen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Barbell Bench Press', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/1.jpg'], array['Houd je schouderbladen samengetrokken en tegen de bank gedrukt.', 'Laat de stang gecontroleerd zakken tot lichte aanraking met je borst.', 'Houd een lichte natuurlijke boog in je onderrug, voeten stevig op de grond.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Bench Press', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/1.jpg'], array['Houd je polsen recht boven je ellebogen tijdens het drukken.', 'Laat de dumbbells niet te ver naar buiten zakken — bescherm je schouders.', 'Druk gelijkmatig met beide armen omhoog, niet asymmetrisch.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Incline Dumbbell Press', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/1.jpg'], array['Zet de bank op 30-45 graden — hoger verschuift de focus te veel naar de schouders.', 'Laat de dumbbells zakken tot net onder schouderhoogte.', 'Houd je onderrug licht in contact met de bank, niet overdreven hol.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Decline Push-up', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Push-Up/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Push-Up/1.jpg'], array['Houd je lichaam in één rechte lijn van hoofd tot voeten.', 'Handen iets breder dan schouderbreedte, vingers licht naar buiten.', 'Zak tot je borst bijna de grond raakt, ellebogen onder ongeveer 45 graden.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Bent-Over Row', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Two-Dumbbell_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Two-Dumbbell_Row/1.jpg'], array['Houd je rug recht en buig vanuit je heupen, niet je onderrug.', 'Trek de dumbbells naar je onderbuik, ellebogen dicht langs je lichaam.', 'Laat het gewicht gecontroleerd terugzakken — geen zwaai.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Inverted Row', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Inverted_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Inverted_Row/1.jpg'], array['Houd je lichaam kaarsrecht, geen doorzakkende heupen.', 'Trek je borst naar de stang, schouderbladen samen.', 'Hoe horizontaler je lichaam, hoe zwaarder de oefening — pas de hoek aan je niveau aan.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Single-Arm Dumbbell Row', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/1.jpg'], array['Steun met je andere hand en knie stabiel op de bank.', 'Trek de dumbbell omhoog richting je heup, niet richting je schouder.', 'Draai je romp niet mee — houd hem stabiel.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Barbell Overhead Press', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Military_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Military_Press/1.jpg'], array['Span je core aan zodat je onderrug niet doorbuigt.', 'Duw de stang recht omhoog en breng je hoofd iets naar achteren als hij passeert.', 'Knijp je billen samen voor extra stabiliteit tijdens het duwen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Shoulder Press', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/1.jpg'], array['Start met de dumbbells op schouderhoogte, ellebogen licht voor je lichaam.', 'Duw de dumbbells omhoog zonder je onderrug te laten doorbuigen.', 'Laat ze gecontroleerd zakken tot net onder schouderhoogte.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Machine Shoulder Press', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Shoulder_Military_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Shoulder_Military_Press/1.jpg'], array['Stel de zitting zo af dat de handvaten op schouderhoogte starten.', 'Houd je rug tegen de rugleuning tijdens de hele beweging.', 'Blokkeer je ellebogen niet hard bovenaan.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Seated Dumbbell Press', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Dumbbell_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Dumbbell_Press/1.jpg'], array['Zorg voor steun in je onderrug via de rugleuning.', 'Duw recht omhoog, laat de dumbbells niet naar voren of achteren zwaaien.', 'Adem uit tijdens het duwen, in tijdens het zakken.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Lat Pulldown', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/1.jpg'], array['Pak de stang iets breder dan schouderbreedte.', 'Trek de stang naar je bovenborst, niet naar je nek.', 'Leun niet ver naar achteren — gebruik je lats, niet je lichaamsgewicht.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Pullover', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent-Arm_Dumbbell_Pullover/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent-Arm_Dumbbell_Pullover/1.jpg'], array['Houd een lichte, gelijkblijvende buiging in je ellebogen.', 'Laat de dumbbell zakken tot achter je hoofd — voel de rek in je lats.', 'Houd je heupen laag, geen brug maken met je onderrug.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Chin-up', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/1.jpg'], array['Grip iets smaller dan schouderbreedte, handpalmen naar je toe.', 'Trek je ellebogen naar beneden en achteren, niet alleen je armen buigen.', 'Zak helemaal uit tot gestrekte armen onderaan.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Chin-up (biceps-focus)', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/1.jpg'], array['Grip iets smaller dan schouderbreedte, handpalmen naar je toe.', 'Trek je ellebogen naar beneden en achteren, niet alleen je armen buigen.', 'Zak helemaal uit tot gestrekte armen onderaan.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Barbell Curl', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/1.jpg'], array['Houd je ellebogen dicht bij je lichaam — ze bewegen niet naar voren.', 'Geen zwaai met je rug of heupen om het gewicht omhoog te krijgen.', 'Laat de stang gecontroleerd terugzakken tot volledig gestrekte armen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Curl', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/1.jpg'], array['Draai je pols licht naar buiten tijdens het optrekken.', 'Houd je bovenarm stil — alleen de onderarm beweegt.', 'Vermijd momentum door je schouders naar achteren te zwaaien.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Cable Curl', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Biceps_Cable_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Biceps_Cable_Curl/1.jpg'], array['Ga niet te ver naar achteren leunen om het gewicht omhoog te trekken.', 'Houd constante spanning op de kabel, ook onderaan de beweging.', 'Ellebogen blijven op dezelfde plek, geen voorwaartse beweging.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Hammer Curl', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls/1.jpg'], array['Houd je handpalmen naar elkaar toe gedurende de hele beweging.', 'Ellebogen dicht bij je lichaam, geen zijwaartse zwaai.', 'Beweeg gecontroleerd omlaag — niet laten vallen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Cable Triceps Pushdown', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/1.jpg'], array['Houd je ellebogen vast tegen je zij — ze bewegen niet mee.', 'Strek je armen volledig door onderaan, zonder te blokkeren.', 'Leun niet met je bovenlichaam mee om extra gewicht te duwen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Skull Crusher', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Skullcrusher/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Skullcrusher/1.jpg'], array['Houd je bovenarmen loodrecht en stil — alleen de onderarmen bewegen.', 'Laat de stang zakken richting je voorhoofd, niet je keel.', 'Gebruik een lichter gewicht dan je gewend bent — dit is een isolatie-oefening.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Kickback', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tricep_Dumbbell_Kickback/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tricep_Dumbbell_Kickback/1.jpg'], array['Houd je bovenarm parallel aan de grond, stil tijdens de hele set.', 'Strek je onderarm volledig naar achteren en knijp de triceps samen.', 'Buig niet mee met je pols — houd hem neutraal.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Bench Dip', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/1.jpg'], array['Houd je heupen dicht bij de bank, niet ver naar voren.', 'Zak tot je ellebogen ongeveer 90 graden buigen.', 'Houd je schouders naar beneden, niet omhoog richting je oren.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Leg Extension', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/1.jpg'], array['Stel de rugleuning zo af dat je knieën in lijn liggen met het draaipunt.', 'Strek je benen volledig, maar blokkeer je knieën niet hard.', 'Laat het gewicht gecontroleerd zakken, niet laten vallen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Step-up', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/1.jpg'], array['Zet je hele voet plat op de step voordat je omhoog duwt.', 'Duw door je hiel van het bovenste been, niet door afzetten met het onderste been.', 'Sta helemaal recht bovenop voordat je weer naar beneden stapt.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Walking Lunge', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Walking_Lunge/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Walking_Lunge/1.jpg'], array['Zet een flinke stap naar voren zodat je knie niet voorbij je tenen komt.', 'Houd je romp rechtop tijdens elke stap.', 'Duw af vanuit je voorste hiel om naar de volgende stap te komen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Hack Squat', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/1.jpg'], array['Zet je voeten iets voor het midden van de plaat, schouderbreedte uit elkaar.', 'Houd je onderrug plat tegen de rugsteun tijdens de hele beweging.', 'Zak tot je heupen net onder kniehoogte komen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Sissy Squat', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Weighted_Sissy_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Weighted_Sissy_Squat/1.jpg'], array['Houd je heupen gestrekt — de beweging komt uit je knieën, niet uit een heupbuiging.', 'Gebruik iets stabiels om je aan vast te houden tot je de balans onder de knie hebt.', 'Zak zo diep als je knieën comfortabel toelaten.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Lying Leg Curl', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/1.jpg'], array['Houd je heupen tegen de bank gedrukt — til ze niet op tijdens het buigen.', 'Buig je knieën volledig door en knijp je hamstrings samen bovenaan.', 'Laat het gewicht gecontroleerd terugzakken.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Stiff-Leg Deadlift', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Dumbbell_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Dumbbell_Deadlift/1.jpg'], array['Houd je knieën licht gebogen en constant — dit is geen kniebuiging.', 'Buig vanuit je heupen, houd de dumbbells dicht langs je benen.', 'Stop met zakken zodra je rug zou gaan bollen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Seated Leg Curl', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/1.jpg'], array['Zorg dat het draaipunt van de machine gelijk ligt met je kniegewricht.', 'Buig je knieën volledig door zonder je heupen mee te bewegen.', 'Laat het gewicht gecontroleerd terug omhoog komen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Standing Calf Raise', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/1.jpg'], array['Kom helemaal omhoog op de bal van je voet.', 'Laat je hielen onderaan iets verder zakken dan de steun voor extra rek.', 'Beweeg gecontroleerd — geen stuiterende herhalingen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Calf Raise', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Calf_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Calf_Raise/1.jpg'], array['Houd de dumbbells stil naast je lichaam, gebruik geen zwaai.', 'Kom volledig omhoog op je tenen en knijp je kuiten samen.', 'Zak rustig terug tot een lichte rek in je kuit.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Seated Calf Raise', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/1.jpg'], array['Zorg dat het kussen net boven je knieën rust, niet erop.', 'Kom volledig omhoog op de bal van je voet.', 'Laat je hielen zo ver mogelijk zakken voor volledige rek.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Cable Crunch', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/1.jpg'], array['Buig vanuit je romp, niet vanuit je heupen — je bekken blijft stil.', 'Houd de kabel dicht bij je hoofd, trek niet met je armen.', 'Adem uit tijdens het naar beneden buigen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Weighted Plank', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/1.jpg'], array['Houd je lichaam in één rechte lijn van hoofd tot hielen.', 'Span je buik en billen actief aan, laat je heupen niet zakken.', 'Adem rustig door — houd je adem niet vast.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Plank', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/1.jpg'], array['Houd je lichaam in één rechte lijn van hoofd tot hielen.', 'Span je buik en billen actief aan, laat je heupen niet zakken.', 'Kijk naar de grond om je nek in een neutrale positie te houden.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Hanging Leg Raise', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/1.jpg'], array['Houd je bovenlichaam stil — vermijd zwaaien tijdens de beweging.', 'Til je benen op door je onderbuik aan te spannen, niet met momentum.', 'Laat je benen gecontroleerd terugzakken, niet laten vallen.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)'),
  ('Dumbbell Russian Twist', array['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/1.jpg'], array['Leun licht naar achteren met een rechte rug, niet gebogen.', 'Draai vanuit je romp, niet alleen met je armen.', 'Til je voeten iets van de grond voor een zwaardere variant.'], 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (public domain)');

